- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: 64943e86417774b9d6ba63c74e00f8cc3e2119e0
  hooks:
    - id: check-ast
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: double-quote-string-fixer
    - id: fix-encoding-pragma
    - id: trailing-whitespace
    - id: name-tests-test

- repo: https://github.com/pre-commit/pre-commit
  sha: cdf726bbedb15f33ca60fdc397fec379946755fc
  hooks:
    - id: validate_config
